name             'django_deploy'
maintainer       'Andrew Remdond'
maintainer_email 'myemail@mydomain.com'
license          'all_rights'
description      'Installs/Configures django_deploy'
long_description 'Installs/Configures django_deploy'
version          '0.1.0'

depends 'python'
depends 'build-essential'
